### ISSUE TITLE
Piped runtime documentation unclear

### ISSUE THREAD

**Issue by SevereOverfl0w** [RutledgePaulV/clj-embed#11]
From the example I'm a little confused:

* Is `runtime` a bound var? Or should it be `r` like the surrounding context
* I'm not fully certain of the intention of it, from the given example. I think it has access to dynamic vars or something, but I'm really not clear.

**Comment by RutledgePaulV** [comment]
Hi, yes `runtime` should be `r` (the runtime instance used by the other examples). I've corrected this, thanks.

The intention of `with-piped-runtime` is for when you want the standard in and standard out dynamic vars within the provided runtime to be bound with the current standard in and standard out  as found in the root runtime. This might be useful to you if you're using a repl and want the in / out within the runtime to prompt from the repl and write to the repl. If you have no need for standard in and standard out to be the same then `(with-runtime r ...)` is otherwise the same.

**Comment by SevereOverfl0w** [comment]
That answered my questions, thanks!
